<?php
function predigern_plugin_override() {

//---------------------------------
if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array (
	'key' => 'group_5497f1499d34a',
	'title' => 'Frontseite',
	'fields' => array (
		array (
			'key' => 'field_54ba84bd89d9f',
			'label' => 'Titel',
			'name' => 'homepage-title',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_54ba86d42035f',
			'label' => 'Kurztitel',
			'name' => 'homepage-short-title',
			'type' => 'text',
			'instructions' => 'Dieser Text, falls vorhanden, wird in Untermenüs	anstatt des Titels verwendet',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_5497f20e20515',
			'label' => 'Inhalt',
			'name' => 'homepage-text',
			'type' => 'wysiwyg',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'tabs' => 'all',
			'toolbar' => 'full',
			'media_upload' => 1,
		),
		array (
			'key' => 'field_549a9f9700f07',
			'label' => 'Feed',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array (
			'key' => 'field_5562fd074670d',
			'label' => 'Reihenfolge',
			'name' => 'feed-ordering',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => 30,
				'class' => '',
				'id' => '',
			),
			'choices' => array (
				'wie eingegeben' => 'wie eingegeben',
				'zeitlich aufsteigend' => 'zeitlich aufsteigend',
			),
			'default_value' => array (
				'' => '',
			),
			'allow_null' => 1,
			'multiple' => 0,
			'ui' => 0,
			'ajax' => 0,
			'placeholder' => '',
			'disabled' => 0,
			'readonly' => 0,
		),
		array (
			'key' => 'field_5497f27f4fc1a',
			'label' => 'Feed',
			'name' => 'homepage-feed',
			'type' => 'repeater',
			'instructions' => 'Liste der Selektionselemente.',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'min' => 3,
			'max' => 10,
			'layout' => 'block',
			'button_label' => 'Eintrag hinzufügen',
			'collapsed' => '',
			'sub_fields' => array (
				array (
					'key' => 'field_54c04ef1c7f90',
					'label' => 'Art',
					'name' => 'selection-criteria',
					'type' => 'select',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => 30,
						'class' => '',
						'id' => '',
					),
					'choices' => array (
						'Einzelbeitrag' => 'Einzelbeitrag',
						'nächster geplanter Beitrag' => 'nächster geplanter Beitrag',
						'zuletzt veröffentlichter Beitrag' => 'zuletzt veröffentlichter Beitrag',
					),
					'default_value' => array (
						'geplante Beiträge' => 'geplante Beiträge',
					),
					'allow_null' => 0,
					'multiple' => 0,
					'ui' => 0,
					'ajax' => 0,
					'placeholder' => '',
					'disabled' => 0,
					'readonly' => 0,
				),
				array (
					'key' => 'field_54c9636b35cd2',
					'label' => 'Einzelbeitrag',
					'name' => 'individual-post',
					'type' => 'post_object',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'field_54c04ef1c7f90',
								'operator' => '==',
								'value' => 'Einzelbeitrag',
							),
						),
					),
					'wrapper' => array (
						'width' => 70,
						'class' => '',
						'id' => '',
					),
					'post_type' => array (
						0 => 'post',
					),
					'taxonomy' => array (
					),
					'allow_null' => 0,
					'multiple' => 0,
					'return_format' => 'object',
					'ui' => 1,
				),
				array (
					'key' => 'field_54c04ef7c7f92',
					'label' => 'Kategorien',
					'name' => 'categories',
					'type' => 'taxonomy',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'field_54c04ef1c7f90',
								'operator' => '!=',
								'value' => 'Einzelbeitrag',
							),
						),
					),
					'wrapper' => array (
						'width' => 43,
						'class' => '',
						'id' => '',
					),
					'taxonomy' => 'category',
					'field_type' => 'multi_select',
					'allow_null' => 0,
					'load_save_terms' => 0,
					'return_format' => 'id',
					'multiple' => 0,
					'add_term' => 1,
					'load_terms' => 0,
					'save_terms' => 0,
				),
				array (
					'key' => 'field_54c04f08c7f95',
					'label' => 'Standortlimitation',
					'name' => 'limit-location',
					'type' => 'taxonomy',
					'instructions' => 'Um nicht nach Standort zu filtern, dieses Feld leer lassen.',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'field_54c04ef1c7f90',
								'operator' => '!=',
								'value' => 'Einzelbeitrag',
							),
						),
					),
					'wrapper' => array (
						'width' => 23,
						'class' => '',
						'id' => '',
					),
					'taxonomy' => 'location-category',
					'field_type' => 'select',
					'allow_null' => 1,
					'add_term' => 1,
					'load_save_terms' => 0,
					'return_format' => 'id',
					'multiple' => 0,
					'load_terms' => 0,
					'save_terms' => 0,
				),
			),
		),
		array (
			'key' => 'field_549a9f9d00f08',
			'label' => 'Links',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array (
			'key' => 'field_54a7e29179c2a',
			'label' => 'Links',
			'name' => 'links',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'min' => '',
			'max' => '',
			'layout' => 'row',
			'button_label' => 'Eintrag hinzufügen',
			'collapsed' => '',
			'sub_fields' => array (
				array (
					'key' => 'field_54a7e29179c2b',
					'label' => 'Typ',
					'name' => 'type',
					'type' => 'radio',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array (
						'Kontaktperson' => 'Kontaktperson',
						'Standort' => 'Standort',
						'Seite/Beitrag' => 'Seite/Beitrag',
						'Medienbeitrag' => 'Medienbeitrag',
						'Link' => 'Link',
					),
					'other_choice' => 0,
					'save_other_choice' => 0,
					'default_value' => '',
					'layout' => 'horizontal',
					'allow_null' => 0,
				),
				array (
					'key' => 'field_54a7e29179c2c',
					'label' => 'Kontaktperson',
					'name' => 'contact-person',
					'type' => 'post_object',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'field_54a7e29179c2b',
								'operator' => '==',
								'value' => 'Kontaktperson',
							),
						),
					),
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'post_type' => array (
						0 => 'person',
					),
					'taxonomy' => array (
					),
					'allow_null' => 0,
					'multiple' => 0,
					'return_format' => 'object',
					'ui' => 1,
				),
				array (
					'key' => 'field_54c036cdc6446',
					'label' => 'Standort',
					'name' => 'location',
					'type' => 'post_object',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'field_54a7e29179c2b',
								'operator' => '==',
								'value' => 'Standort',
							),
						),
					),
					'wrapper' => array (
						'width' => 25,
						'class' => '',
						'id' => '',
					),
					'post_type' => array (
						0 => 'location',
					),
					'taxonomy' => array (
					),
					'allow_null' => 0,
					'multiple' => 0,
					'return_format' => 'object',
					'ui' => 1,
				),
				array (
					'key' => 'field_54a7e29179c2d',
					'label' => 'Seite/Beitrag',
					'name' => 'post',
					'type' => 'post_object',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'field_54a7e29179c2b',
								'operator' => '==',
								'value' => 'Seite/Beitrag',
							),
						),
					),
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'post_type' => array (
						0 => 'page',
						1 => 'post',
					),
					'taxonomy' => array (
					),
					'allow_null' => 0,
					'multiple' => 0,
					'return_format' => 'object',
					'ui' => 1,
				),
				array (
					'key' => 'field_54a7e29179c2e',
					'label' => 'Medienbeitrag',
					'name' => 'media-item',
					'type' => 'file',
					'instructions' => 'Eine Referenz auf ein Dokument in der Medien-Bibliothek',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'field_54a7e29179c2b',
								'operator' => '==',
								'value' => 'Medienbeitrag',
							),
						),
					),
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'array',
					'library' => 'all',
					'min_size' => 0,
					'max_size' => 0,
					'mime_types' => '',
				),
				array (
					'key' => 'field_54a7e29179c2f',
					'label' => 'Link',
					'name' => 'link-url',
					'type' => 'url',
					'instructions' => 'Volle URL im Format "http://example.com/page"',
					'required' => 1,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'field_54a7e29179c2b',
								'operator' => '==',
								'value' => 'Link',
							),
						),
					),
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
				),
				array (
					'key' => 'field_54a7e29179c32',
					'label' => 'Alternativtext',
					'name' => 'alt',
					'type' => 'text',
					'instructions' => 'Wird als Linktext verwendet, falls eingetragen',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
					'readonly' => 0,
					'disabled' => 0,
				),
			),
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'options_page',
				'operator' => '==',
				'value' => 'homepage',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'acf_after_title',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => array (
		0 => 'custom_fields',
		1 => 'discussion',
		2 => 'comments',
		3 => 'revisions',
		4 => 'format',
		5 => 'tags',
		6 => 'send-trackbacks',
	),
	'active' => 1,
	'description' => '',
	'local' => 'php',
));

acf_add_local_field_group(array (
	'key' => 'group_549c1a209a24f',
	'title' => 'Kategorien-Einstellungen',
	'fields' => array (
		array (
			'key' => 'field_54a813fd5b97c',
			'label' => 'Kategorie als Untertitel',
			'name' => 'use-as-subtitle',
			'type' => 'true_false',
			'instructions' => 'Falls ausgewählt, wird der Kategorie-Name als Beitrags-Untertitel eingeblendet',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 0,
		),
		array (
			'key' => 'field_54ce3cb301446',
			'label' => 'Kategorie-Beitragsbild',
			'name' => 'category-post-image',
			'type' => 'image',
			'instructions' => 'Dieses Grossbild (Formfaktor 1:2) wird für einen Beitrag angezeigt, falls für diesen kein Beitragsbild definiert wurde. Das Bild sollte eine Mindestgrösse von 1500 x 750 px (Breite mal Höhe) aufweisen (Maximalgrösse: 2000 x 1000 px)',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'array',
			'preview_size' => 'medium',
			'library' => 'all',
			'min_width' => 0,
			'min_height' => 0,
			'min_size' => 0,
			'max_width' => 0,
			'max_height' => 0,
			'max_size' => 0,
			'mime_types' => '',
		),
		array (
			'key' => 'field_5499ad9153fae',
			'label' => 'Seite/Beitrag',
			'name' => 'post',
			'type' => 'post_object',
			'instructions' => 'Falls vorhanden wird dieser Link für die referenzierte Kategorie (und alle Unterkategorien) angewendet',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => 50,
				'class' => '',
				'id' => '',
			),
			'post_type' => array (
				0 => 'page',
				1 => 'post',
			),
			'taxonomy' => array (
			),
			'allow_null' => 1,
			'multiple' => 0,
			'return_format' => 'object',
			'ui' => 1,
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'taxonomy',
				'operator' => '==',
				'value' => 'category',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => array (
		0 => 'custom_fields',
		1 => 'discussion',
		2 => 'comments',
		3 => 'revisions',
		4 => 'slug',
		5 => 'format',
		6 => 'page_attributes',
		7 => 'tags',
		8 => 'send-trackbacks',
	),
	'active' => 1,
	'description' => '',
	'local' => 'php',
));

acf_add_local_field_group(array (
	'key' => 'group_54aef6e17e076',
	'title' => 'Optionen',
	'fields' => array (
		array (
			'key' => 'field_5499ad91327ed',
			'label' => 'Hauptmenü',
			'name' => 'hauptmenu',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array (
			'key' => 'field_5499ad913285d',
			'label' => 'Hauptmenü',
			'name' => 'primary-menu',
			'type' => 'repeater',
			'instructions' => 'Vertikales Menü der Seiten, zu denen gesprungen werden kann',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'min' => '',
			'max' => '',
			'layout' => 'table',
			'button_label' => 'Eintrag hinzufügen',
			'collapsed' => '',
			'sub_fields' => array (
				array (
					'key' => 'field_54a2e4011eea9',
					'label' => 'Trennung',
					'name' => 'divider',
					'type' => 'true_false',
					'instructions' => 'Menü-Trennung einfügen',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => 10,
						'class' => '',
						'id' => '',
					),
					'message' => '',
					'default_value' => 0,
				),
				array (
					'key' => 'field_5499ad91425c0',
					'label' => 'Seite/Beitrag',
					'name' => 'page',
					'type' => 'post_object',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'field_54a2e4011eea9',
								'operator' => '!=',
								'value' => '1',
							),
						),
					),
					'wrapper' => array (
						'width' => 35,
						'class' => '',
						'id' => '',
					),
					'post_type' => array (
						0 => 'page',
						1 => 'post',
					),
					'taxonomy' => array (
					),
					'allow_null' => 0,
					'multiple' => 0,
					'return_format' => 'object',
					'ui' => 1,
				),
				array (
					'key' => 'field_5499ad914263d',
					'label' => 'Alternativtext',
					'name' => 'alt',
					'type' => 'text',
					'instructions' => 'Menübezeichnung der Seite (an der Frontseite) – falls leer, wird der Seitenname benutzt',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'field_54a2e4011eea9',
								'operator' => '!=',
								'value' => '1',
							),
						),
					),
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
					'readonly' => 0,
					'disabled' => 0,
				),
			),
		),
		array (
			'key' => 'field_5499ad91328cc',
			'label' => 'Nebenmenü',
			'name' => 'nebenmenu',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array (
			'key' => 'field_5499ad913293e',
			'label' => 'Nebenmenü',
			'name' => 'secondary-menu',
			'type' => 'repeater',
			'instructions' => 'Horizontales Menü der Seiten, zu denen gesprungen werden kann',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'min' => '',
			'max' => '',
			'layout' => 'table',
			'button_label' => 'Eintrag hinzufügen',
			'collapsed' => '',
			'sub_fields' => array (
				array (
					'key' => 'field_54a2ef31e9628',
					'label' => 'Trennung',
					'name' => 'divider',
					'type' => 'true_false',
					'instructions' => 'Menü-Trennung einfügen',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => 10,
						'class' => '',
						'id' => '',
					),
					'message' => '',
					'default_value' => 0,
				),
				array (
					'key' => 'field_5499ad914ad98',
					'label' => 'Seite/Beitrag',
					'name' => 'page',
					'type' => 'post_object',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'field_54a2ef31e9628',
								'operator' => '!=',
								'value' => '1',
							),
						),
					),
					'wrapper' => array (
						'width' => 35,
						'class' => '',
						'id' => '',
					),
					'post_type' => array (
						0 => 'page',
						1 => 'post',
					),
					'taxonomy' => array (
					),
					'allow_null' => 0,
					'multiple' => 0,
					'return_format' => 'object',
					'ui' => 1,
				),
				array (
					'key' => 'field_5499ad914ae18',
					'label' => 'Alternativtext',
					'name' => 'alt',
					'type' => 'text',
					'instructions' => 'Menübezeichnung der Seite',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'field_54a2ef31e9628',
								'operator' => '!=',
								'value' => '1',
							),
						),
					),
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
					'readonly' => 0,
					'disabled' => 0,
				),
			),
		),
		array (
			'key' => 'field_54a3b2bca6c15',
			'label' => 'Umleitungen',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array (
			'key' => 'field_54a3b2d8a6c16',
			'label' => 'Umleitungen',
			'name' => 'redirections',
			'type' => 'repeater',
			'instructions' => 'Umleitungen werden gegenüber gewöhnlichen Seiten bevorzugt. NB: Groß- und Kleinschreibung wird beachtet.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'min' => '',
			'max' => '',
			'layout' => 'table',
			'button_label' => 'Eintrag hinzufügen',
			'collapsed' => '',
			'sub_fields' => array (
				array (
					'key' => 'field_54a3b342a6c17',
					'label' => 'Pfad',
					'name' => 'path',
					'type' => 'text',
					'instructions' => 'Pfad (alphanumerisch, "-" und "_" erlaubt, ohne "/", Klein- und Grossschreibung massgeblich). Der erste Buchstabe muss gross geschrieben sein',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => 40,
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
					'readonly' => 0,
					'disabled' => 0,
				),
				array (
					'key' => 'field_54a3b3d3a6c18',
					'label' => 'Seite/Beitrag',
					'name' => 'post',
					'type' => 'post_object',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'post_type' => array (
						0 => 'page',
						1 => 'post',
					),
					'taxonomy' => array (
					),
					'allow_null' => 0,
					'multiple' => 0,
					'return_format' => 'object',
					'ui' => 1,
				),
			),
		),
		array (
			'key' => 'field_54ce333e7491e',
			'label' => 'Standartwerte',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array (
			'key' => 'field_5497f15e20514',
			'label' => 'Standart-Beitragsbild',
			'name' => 'default-post-image',
			'type' => 'image',
			'instructions' => 'Dieses Grossbild (Formfaktor 1:2) wird für einen Beitrag angezeigt, falls für diesen kein Beitragsbild definiert wurde und keine Kategorienbilder vorhanden sind. Das Bild sollte eine Mindestgrösse von 1500 x 750 px (Breite mal Höhe) aufweisen (Maximalgrösse: 2000 x 1000 px)',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'array',
			'preview_size' => 'medium',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
		array (
			'key' => 'field_54ce33c51acb4',
			'label' => 'Standart-Seitenbild',
			'name' => 'default-page-image',
			'type' => 'image',
			'instructions' => 'Dieses Grossbild (Formfaktor 1:3) wird für eine Seite angezeigt, falls für diese kein Beitragsbild definiert wurde. Das Bild sollte eine Mindestgrösse von 1500 x 500 px (Breite mal Höhe) aufweisen (Maximalgrösse: 2001 x 667 px)',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'array',
			'preview_size' => 'medium',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
		array (
			'key' => 'field_551c3f7e45e63',
			'label' => 'Standart-Portrait',
			'name' => 'default-portrait-image',
			'type' => 'image',
			'instructions' => 'Dieses Bild (Formfaktor 4:3) wird für Personen angezeigt, falls für diese kein Beitragsbild definiert wurde. Das Bild sollte eine Mindestgrösse von 150 x 200 px (Breite mal Höhe) aufweisen (Maximalgrösse: 450 x 600 px)',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'array',
			'preview_size' => 'thumbnail',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
		array (
			'key' => 'field_5508912d91e9f',
			'label' => 'Website-Logo',
			'name' => 'website-logo',
			'type' => 'image',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'array',
			'preview_size' => 'thumbnail',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'options_page',
				'operator' => '==',
				'value' => 'config',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
	'local' => 'php',
));

acf_add_local_field_group(array (
	'key' => 'group_54aea81234bc2',
	'title' => 'Personen-Einstellungen',
	'fields' => array (
		array (
			'key' => 'field_54aea9f0bb9e7',
			'label' => 'Details',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array (
			'key' => 'field_54a111deaf081',
			'label' => 'Rolle',
			'name' => 'role',
			'type' => 'text',
			'instructions' => 'Die normale(n) Rolle(n) dieser Person in der Predigerkirche',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => 20,
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_54b120fd5676e',
			'label' => 'Telefon (M)',
			'name' => 'telephone-mobile',
			'type' => 'text',
			'instructions' => 'Mobile Telefonnummer. Format 07x xxx xx xx',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => 15,
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_54a112095dcf3',
			'label' => 'Telefon (P)',
			'name' => 'telephone-private',
			'type' => 'text',
			'instructions' => 'Private Telefonnummer. Format 044 xxx xx xx',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => 15,
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_54a112315dcf4',
			'label' => 'Telefon (G)',
			'name' => 'telephone-work',
			'type' => 'text',
			'instructions' => 'Geschäftliche Telefonnummer. Format 044 xxx xx xx',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => 15,
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_54a112405dcf5',
			'label' => 'Email-Adresse',
			'name' => 'email-address',
			'type' => 'email',
			'instructions' => 'Die Email-Adresse, über die diese Person kontaktiert werden darf. NB: Die Postadresse und andere Details dieser Person können fakultativ als Textinhalt zum Beitrag eingegeben werden',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => 25,
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'person',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => array (
		0 => 'custom_fields',
		1 => 'discussion',
		2 => 'comments',
		3 => 'revisions',
		4 => 'slug',
		5 => 'format',
		6 => 'page_attributes',
		7 => 'tags',
		8 => 'send-trackbacks',
	),
	'active' => 1,
	'description' => '',
	'local' => 'php',
));

acf_add_local_field_group(array (
	'key' => 'group_54bff445381a5',
	'title' => 'Standorts-Einstellungen',
	'fields' => array (
		array (
			'key' => 'field_54bff4d60ae6b',
			'label' => 'Koordinate',
			'name' => 'coordinate',
			'type' => 'google_map',
			'instructions' => 'Kartenkoordinate eines Ortes (click an der richtigen Stelle auf der Karte oder die Adresse eingeben)',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => 60,
				'class' => '',
				'id' => '',
			),
			'center_lat' => '47.37388',
			'center_lng' => '8.545094',
			'zoom' => 18,
			'height' => 300,
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'location',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => array (
		0 => 'discussion',
		1 => 'comments',
		2 => 'revisions',
		3 => 'tags',
		4 => 'send-trackbacks',
	),
	'active' => 1,
	'description' => '',
	'local' => 'php',
));

acf_add_local_field_group(array (
	'key' => 'group_5497fe25d7cf1',
	'title' => 'Beitrags-Einstellungen',
	'fields' => array (
		array (
			'key' => 'field_5499a57f19e12',
			'label' => 'Details zum Beitrag',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array (
			'key' => 'field_54c00407910cd',
			'label' => 'Zeitangaben',
			'name' => 'time-settings',
			'type' => 'radio',
			'instructions' => 'Welche Zeitangaben sind für diesen Beitrag relevant',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array (
				'keine' => 'keine',
				'Datum und Zeit' => 'Datum und Zeit',
				'nur Datum' => 'nur Datum',
				'Zeitraum' => 'Zeitraum',
				'Zeitraum mit Zeiten' => 'Zeitraum mit Zeiten',
				'wöchentlich wiederholend' => 'wöchentlich wiederholend',
			),
			'other_choice' => 0,
			'save_other_choice' => 0,
			'default_value' => 'Datum und Zeit',
			'layout' => 'horizontal',
			'allow_null' => 0,
		),
		array (
			'key' => 'field_54aaf532c2616',
			'label' => 'Startdatum',
			'name' => 'post-start-date',
			'type' => 'date_picker',
			'instructions' => 'Am welchen oder ab welchem Datum findet dieser Beitrag statt / soll dieser Beitrag publiziert werden',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => 25,
				'class' => '',
				'id' => '',
			),
			'display_format' => 'd.m.Y',
			'return_format' => 'Y-m-d',
			'first_day' => 1,
		),
		array (
			'key' => 'field_54c004d0910ce',
			'label' => 'Startzeit',
			'name' => 'post-start-time',
			'type' => 'time_picker',
			'instructions' => 'Zu welcher Uhrzeit findet dieser Beitrag statt',
			'required' => 1,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_54c00407910cd',
						'operator' => '!=',
						'value' => 'keine',
					),
					array (
						'field' => 'field_54c00407910cd',
						'operator' => '!=',
						'value' => 'nur Datum',
					),
					array (
						'field' => 'field_54c00407910cd',
						'operator' => '!=',
						'value' => 'Zeitraum',
					),
				),
			),
			'wrapper' => array (
				'width' => 20,
				'class' => '',
				'id' => '',
			),
			'display_format' => 'H:i',
			'return_format' => 'H:i',
		),
		array (
			'key' => 'field_54ba893a7cabc',
			'label' => 'wöchentlich wiederholen',
			'name' => 'weekly-repeat',
			'type' => 'checkbox',
			'instructions' => 'Der Beitrag findet wöchentlich zur gleichen Startzeit vom Startdatum bis zum Enddatum im angegebenen Tagesmuster statt',
			'required' => 1,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_54c00407910cd',
						'operator' => '==',
						'value' => 'wöchentlich wiederholend',
					),
				),
			),
			'wrapper' => array (
				'width' => 15,
				'class' => '',
				'id' => '',
			),
			'choices' => array (
				'Mo' => 'Mo',
				'Di' => 'Di',
				'Mi' => 'Mi',
				'Do' => 'Do',
				'Fr' => 'Fr',
				'Sa' => 'Sa',
				'So' => 'So',
			),
			'default_value' => array (
				'' => '',
			),
			'layout' => 'vertical',
			'toggle' => 0,
		),
		array (
			'key' => 'field_5651bcfe9deb1',
			'label' => 'alle x Wochen',
			'name' => 'every_x_weeks',
			'type' => 'number',
			'instructions' => 'Die Wiederholungen finden nur alle x Wochen statt, wo "x" ist der hier gesetzte Wert. Wenn "0" gesetzt ist, nur die Daten in der Ausnahmenliste werden setzt',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_54c00407910cd',
						'operator' => '==',
						'value' => 'wöchentlich wiederholend',
					),
				),
			),
			'wrapper' => array (
				'width' => 10,
				'class' => '',
				'id' => '',
			),
			'default_value' => 1,
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'min' => 0,
			'max' => 4,
			'step' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_551aed103c4d2',
			'label' => 'Enddatum',
			'name' => 'post-end-date',
			'type' => 'date_picker',
			'instructions' => 'Der Beitrag wird auch in "geplanten" Feeds bis zu diesem Datum angezeigt. Für wöchentlich wiederholende Beiträge definiert diese Feld das letztmögliche WIederholungsdatum',
			'required' => 1,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_54c00407910cd',
						'operator' => '!=',
						'value' => 'keine',
					),
					array (
						'field' => 'field_54c00407910cd',
						'operator' => '!=',
						'value' => 'Datum und Zeit',
					),
					array (
						'field' => 'field_54c00407910cd',
						'operator' => '!=',
						'value' => 'nur Datum',
					),
				),
			),
			'wrapper' => array (
				'width' => 25,
				'class' => '',
				'id' => '',
			),
			'display_format' => 'd.m.Y',
			'return_format' => 'Y-m-d',
			'first_day' => 1,
		),
		array (
			'key' => 'field_565398288b98a',
			'label' => 'Ausnahmen',
			'name' => 'exceptions',
			'type' => 'text',
			'instructions' => 'Eine Liste von Ausnahme-Daten (zwischen Start- und Enddatum) getrennt durch Kommas. Wenn ein Datum in de Liste mit keinem regelmässigen Termin übereinstimmt, wird der Termin ausnahmsweise aktiviert, wenn es mit einem regelmässigen Termin übereinstimmt, wird der regelmässiger Termin unterdrückt. Datumsformate mit vierstelliger Jahrzahl verwenden',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_54c00407910cd',
						'operator' => '==',
						'value' => 'wöchentlich wiederholend',
					),
				),
			),
			'wrapper' => array (
				'width' => 70,
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_551aa1abe28b8',
			'label' => 'Endzeit',
			'name' => 'post-end-time',
			'type' => 'time_picker',
			'instructions' => 'Zu welcher Uhrzeit endet dieser Beitrag',
			'required' => 1,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_54c00407910cd',
						'operator' => '==',
						'value' => 'Zeitraum mit Zeiten',
					),
				),
			),
			'wrapper' => array (
				'width' => 20,
				'class' => '',
				'id' => '',
			),
			'display_format' => 'H:i',
			'return_format' => 'H:i',
		),
		array (
			'key' => 'field_549ae414413a6',
			'label' => 'Standort',
			'name' => 'post-location',
			'type' => 'post_object',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => 25,
				'class' => '',
				'id' => '',
			),
			'post_type' => array (
				0 => 'location',
			),
			'taxonomy' => array (
			),
			'allow_null' => 1,
			'multiple' => 0,
			'return_format' => 'object',
			'ui' => 1,
		),
		array (
			'key' => 'field_54a860b53b747',
			'label' => 'Mitwirkende',
			'name' => 'contributors',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => '',
			'min' => '',
			'max' => '',
			'layout' => 'block',
			'button_label' => 'Eintrag hinzufügen',
			'sub_fields' => array (
				array (
					'key' => 'field_54a865a99d324',
					'label' => 'Interne Person',
					'name' => 'person-is-internal',
					'type' => 'true_false',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => 15,
						'class' => '',
						'id' => '',
					),
					'message' => '',
					'default_value' => 1,
				),
				array (
					'key' => 'field_54a860db3b748',
					'label' => 'Person',
					'name' => 'person',
					'type' => 'post_object',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'field_54a865a99d324',
								'operator' => '==',
								'value' => '1',
							),
						),
					),
					'wrapper' => array (
						'width' => 40,
						'class' => '',
						'id' => '',
					),
					'post_type' => array (
						0 => 'person',
					),
					'taxonomy' => array (
					),
					'allow_null' => 1,
					'multiple' => 0,
					'return_format' => 'object',
					'ui' => 1,
				),
				array (
					'key' => 'field_54a8661f9d325',
					'label' => 'Person',
					'name' => 'external-person',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'field_54a865a99d324',
								'operator' => '!=',
								'value' => '1',
							),
						),
					),
					'wrapper' => array (
						'width' => 40,
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
					'readonly' => 0,
					'disabled' => 0,
				),
				array (
					'key' => 'field_54a8611a3b749',
					'label' => 'Rolle',
					'name' => 'contributors-role',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => 40,
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
					'readonly' => 0,
					'disabled' => 0,
				),
			),
		),
		array (
			'key' => 'field_54a015fff4dfd',
			'label' => 'Annulliert',
			'name' => 'cancelled',
			'type' => 'true_false',
			'instructions' => 'Falls gesetzt, wird der Beitrag als "annulliert" angezeigt',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 0,
		),
		array (
			'key' => 'field_549ac396c9f81',
			'label' => 'Bildergallerie',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array (
			'key' => 'field_549ac4f8149e0',
			'label' => 'Gallerie',
			'name' => 'gallery',
			'type' => 'gallery',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'min' => '',
			'max' => '',
			'preview_size' => 'thumbnail',
			'library' => 'all',
			'min_width' => 0,
			'min_height' => 0,
			'min_size' => 0,
			'max_width' => 0,
			'max_height' => 0,
			'max_size' => 0,
			'mime_types' => '',
			'insert' => 'append',
		),
		array (
			'key' => 'field_54a41fc1be596',
			'label' => 'Links',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array (
			'key' => 'field_54a41fc5be597',
			'label' => 'Links',
			'name' => 'links',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'min' => '',
			'max' => '',
			'layout' => 'row',
			'button_label' => 'Eintrag hinzufügen',
			'collapsed' => '',
			'sub_fields' => array (
				array (
					'key' => 'field_54a41fc5be598',
					'label' => 'Typ',
					'name' => 'type',
					'type' => 'radio',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => 15,
						'class' => '',
						'id' => '',
					),
					'choices' => array (
						'Kontaktperson' => 'Kontaktperson',
						'Standort' => 'Standort',
						'Seite/Beitrag' => 'Seite/Beitrag',
						'Medienbeitrag' => 'Medienbeitrag',
						'Link' => 'Link',
					),
					'other_choice' => 0,
					'save_other_choice' => 0,
					'default_value' => '',
					'layout' => 'horizontal',
					'allow_null' => 0,
				),
				array (
					'key' => 'field_54a41fc5be599',
					'label' => 'Kontaktperson',
					'name' => 'contact-person',
					'type' => 'post_object',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'field_54a41fc5be598',
								'operator' => '==',
								'value' => 'Kontaktperson',
							),
						),
					),
					'wrapper' => array (
						'width' => 25,
						'class' => '',
						'id' => '',
					),
					'post_type' => array (
						0 => 'person',
					),
					'taxonomy' => array (
					),
					'allow_null' => 0,
					'multiple' => 0,
					'return_format' => 'object',
					'ui' => 1,
				),
				array (
					'key' => 'field_54c036b2a0f6a',
					'label' => 'Standort',
					'name' => 'location',
					'type' => 'post_object',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'field_54a41fc5be598',
								'operator' => '==',
								'value' => 'Standort',
							),
						),
					),
					'wrapper' => array (
						'width' => 25,
						'class' => '',
						'id' => '',
					),
					'post_type' => array (
						0 => 'location',
					),
					'taxonomy' => array (
					),
					'allow_null' => 0,
					'multiple' => 0,
					'return_format' => 'object',
					'ui' => 1,
				),
				array (
					'key' => 'field_54a41fc5be59b',
					'label' => 'Seite/Beitrag',
					'name' => 'post',
					'type' => 'post_object',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'field_54a41fc5be598',
								'operator' => '==',
								'value' => 'Seite/Beitrag',
							),
						),
					),
					'wrapper' => array (
						'width' => 25,
						'class' => '',
						'id' => '',
					),
					'post_type' => array (
						0 => 'page',
						1 => 'post',
					),
					'taxonomy' => array (
					),
					'allow_null' => 0,
					'multiple' => 0,
					'return_format' => 'object',
					'ui' => 1,
				),
				array (
					'key' => 'field_54a723b216d5e',
					'label' => 'Medienbeitrag',
					'name' => 'media-item',
					'type' => 'file',
					'instructions' => 'Eine Referenz auf ein Dokument in der Medien-Bibliothek',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'field_54a41fc5be598',
								'operator' => '==',
								'value' => 'Medienbeitrag',
							),
						),
					),
					'wrapper' => array (
						'width' => 25,
						'class' => '',
						'id' => '',
					),
					'return_format' => 'array',
					'library' => 'all',
					'min_size' => 0,
					'max_size' => 0,
					'mime_types' => '',
				),
				array (
					'key' => 'field_54a41fc5be59c',
					'label' => 'Link',
					'name' => 'link-url',
					'type' => 'url',
					'instructions' => 'Volle URL im Format "http://example.com/page"',
					'required' => 1,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'field_54a41fc5be598',
								'operator' => '==',
								'value' => 'Link',
							),
						),
					),
					'wrapper' => array (
						'width' => 25,
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
				),
				array (
					'key' => 'field_54a41fc5be59d',
					'label' => 'Alternativtext',
					'name' => 'alt',
					'type' => 'text',
					'instructions' => 'Wird als Linktext verwendet, falls eingetragen',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => 25,
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
					'readonly' => 0,
					'disabled' => 0,
				),
			),
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'post',
			),
		),
	),
	'menu_order' => 10,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => array (
		0 => 'custom_fields',
		1 => 'discussion',
		2 => 'comments',
		3 => 'revisions',
		4 => 'slug',
		5 => 'format',
		6 => 'page_attributes',
		7 => 'tags',
		8 => 'send-trackbacks',
	),
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array (
	'key' => 'group_5498083b66733',
	'title' => 'Seiten-Einstellungen',
	'fields' => array (
		array (
			'key' => 'field_54da7cdb6ee59',
			'label' => 'Allgemein',
			'name' => 'seiten-einstellungen',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array (
			'key' => 'field_54da719000cdb',
			'label' => 'Link zur übergeordneten Seite nicht anzeigen',
			'name' => 'suppress-uplink',
			'type' => 'true_false',
			'instructions' => 'Falls ausgewählt, wird der Link zur übergeordneten Seite im Untermenü *nicht* angezeigt',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 0,
		),
		array (
			'key' => 'field_54aef94742734',
			'label' => 'Kurztitel',
			'name' => 'short-title',
			'type' => 'text',
			'instructions' => 'Dieser Text, falls vorhanden, wird in Untermenüs	anstatt des Titels verwendet',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_54a4217052034',
			'label' => 'Feed',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array (
			'key' => 'field_54a4217352036',
			'label' => 'Art',
			'name' => 'feed-type',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => 30,
				'class' => '',
				'id' => '',
			),
			'choices' => array (
				'geplante Beiträge' => 'geplante Beiträge',
				'veröffentlichte Beiträge' => 'veröffentlichte Beiträge',
				'Media' => 'Media',
				'Media absteigend' => 'Media absteigend',
				'Personen' => 'Personen',
				'Standorte' => 'Standorte',
			),
			'default_value' => array (
				'' => '',
			),
			'allow_null' => 1,
			'multiple' => 0,
			'ui' => 0,
			'ajax' => 0,
			'placeholder' => '',
			'disabled' => 0,
			'readonly' => 0,
		),
		array (
			'key' => 'field_54a4217352037',
			'label' => 'Titel',
			'name' => 'feed-title',
			'type' => 'text',
			'instructions' => 'Titel über dem Feed.',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_54a4217352036',
						'operator' => '!=',
						'value' => '',
					),
				),
			),
			'wrapper' => array (
				'width' => 65,
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_54a4217352038',
			'label' => 'Beitragskategorien',
			'name' => 'categories',
			'type' => 'taxonomy',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_54a4217352036',
						'operator' => '!=',
						'value' => 'Personen',
					),
					array (
						'field' => 'field_54a4217352036',
						'operator' => '!=',
						'value' => 'Standorte',
					),
					array (
						'field' => 'field_54a4217352036',
						'operator' => '!=',
						'value' => '',
					),
				),
			),
			'wrapper' => array (
				'width' => 25,
				'class' => '',
				'id' => '',
			),
			'taxonomy' => 'category',
			'field_type' => 'multi_select',
			'allow_null' => 1,
			'add_term' => 1,
			'load_save_terms' => 0,
			'return_format' => 'id',
			'multiple' => 0,
			'load_terms' => 0,
			'save_terms' => 0,
		),
		array (
			'key' => 'field_54b12ec00ab45',
			'label' => 'Personenkategorien',
			'name' => 'person-categories',
			'type' => 'taxonomy',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_54a4217352036',
						'operator' => '==',
						'value' => 'Personen',
					),
				),
			),
			'wrapper' => array (
				'width' => 25,
				'class' => '',
				'id' => '',
			),
			'taxonomy' => 'person-category',
			'field_type' => 'multi_select',
			'allow_null' => 1,
			'add_term' => 1,
			'load_save_terms' => 0,
			'return_format' => 'id',
			'multiple' => 0,
			'load_terms' => 0,
			'save_terms' => 0,
		),
		array (
			'key' => 'field_54c039c09503f',
			'label' => 'Standortkategorien',
			'name' => 'location-categories',
			'type' => 'taxonomy',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_54a4217352036',
						'operator' => '==',
						'value' => 'Standorte',
					),
				),
			),
			'wrapper' => array (
				'width' => 25,
				'class' => '',
				'id' => '',
			),
			'taxonomy' => 'location-category',
			'field_type' => 'multi_select',
			'allow_null' => 1,
			'add_term' => 1,
			'load_save_terms' => 0,
			'return_format' => 'id',
			'multiple' => 0,
			'load_terms' => 0,
			'save_terms' => 0,
		),
		array (
			'key' => 'field_55745435f7ea0',
			'label' => 'Digitale Broschüre',
			'name' => 'booklet',
			'type' => 'true_false',
			'instructions' => 'Wenn gesetzt, werden Mediendateien wie eine Zeitung angezeigt',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_54a4217352036',
						'operator' => '==',
						'value' => 'Media',
					),
				),
				array (
					array (
						'field' => 'field_54a4217352036',
						'operator' => '==',
						'value' => 'Media absteigend',
					),
				),
			),
			'wrapper' => array (
				'width' => 25,
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 0,
		),
		array (
			'key' => 'field_54a421735203b',
			'label' => 'Maximale Anzahl Beiträge',
			'name' => 'feed-limit',
			'type' => 'number',
			'instructions' => 'Die maximale Anzahl Beiträge zum Anzeigen',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_54a4217352036',
						'operator' => '!=',
						'value' => '',
					),
				),
			),
			'wrapper' => array (
				'width' => 25,
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'min' => 1,
			'max' => 20,
			'step' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_54a421735203c',
			'label' => 'Limitation nach Standort',
			'name' => 'limit-location',
			'type' => 'taxonomy',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_54a4217352036',
						'operator' => '!=',
						'value' => 'Media',
					),
					array (
						'field' => 'field_54a4217352036',
						'operator' => '!=',
						'value' => 'Media absteigend',
					),
					array (
						'field' => 'field_54a4217352036',
						'operator' => '!=',
						'value' => 'Personen',
					),
					array (
						'field' => 'field_54a4217352036',
						'operator' => '!=',
						'value' => 'Standorte',
					),
					array (
						'field' => 'field_54a4217352036',
						'operator' => '!=',
						'value' => '',
					),
				),
			),
			'wrapper' => array (
				'width' => 25,
				'class' => '',
				'id' => '',
			),
			'taxonomy' => 'location-category',
			'field_type' => 'select',
			'allow_null' => 1,
			'load_save_terms' => 0,
			'return_format' => 'id',
			'multiple' => 0,
			'add_term' => 1,
			'load_terms' => 0,
			'save_terms' => 0,
		),
		array (
			'key' => 'field_549ac541e6667',
			'label' => 'Bildergallerie',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array (
			'key' => 'field_549ac23a1f83e',
			'label' => 'Gallerie',
			'name' => 'gallery',
			'type' => 'gallery',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'min' => '',
			'max' => '',
			'preview_size' => 'thumbnail',
			'library' => 'all',
			'min_width' => 0,
			'min_height' => 0,
			'min_size' => 0,
			'max_width' => 0,
			'max_height' => 0,
			'max_size' => 0,
			'mime_types' => '',
			'insert' => 'append',
		),
		array (
			'key' => 'field_54a41f9855eb2',
			'label' => 'Links',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array (
			'key' => 'field_54a7e2a2e2624',
			'label' => 'Links',
			'name' => 'links',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'min' => '',
			'max' => '',
			'layout' => 'row',
			'button_label' => 'Eintrag hinzufügen',
			'collapsed' => '',
			'sub_fields' => array (
				array (
					'key' => 'field_54a7e2a3e2625',
					'label' => 'Typ',
					'name' => 'type',
					'type' => 'radio',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => 15,
						'class' => '',
						'id' => '',
					),
					'choices' => array (
						'Kontaktperson' => 'Kontaktperson',
						'Standort' => 'Standort',
						'Seite/Beitrag' => 'Seite/Beitrag',
						'Medienbeitrag' => 'Medienbeitrag',
						'Link' => 'Link',
					),
					'other_choice' => 0,
					'save_other_choice' => 0,
					'default_value' => '',
					'layout' => 'horizontal',
					'allow_null' => 0,
				),
				array (
					'key' => 'field_54a7e2a3e2626',
					'label' => 'Kontaktperson',
					'name' => 'contact-person',
					'type' => 'post_object',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'field_54a7e2a3e2625',
								'operator' => '==',
								'value' => 'Kontaktperson',
							),
						),
					),
					'wrapper' => array (
						'width' => 25,
						'class' => '',
						'id' => '',
					),
					'post_type' => array (
						0 => 'person',
					),
					'taxonomy' => array (
					),
					'allow_null' => 0,
					'multiple' => 0,
					'return_format' => 'object',
					'ui' => 1,
				),
				array (
					'key' => 'field_54c035e770dce',
					'label' => 'Standort',
					'name' => 'location',
					'type' => 'post_object',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'field_54a7e2a3e2625',
								'operator' => '==',
								'value' => 'Standort',
							),
						),
					),
					'wrapper' => array (
						'width' => 25,
						'class' => '',
						'id' => '',
					),
					'post_type' => array (
						0 => 'location',
					),
					'taxonomy' => array (
					),
					'allow_null' => 0,
					'multiple' => 0,
					'return_format' => 'object',
					'ui' => 1,
				),
				array (
					'key' => 'field_54a7e2a3e2627',
					'label' => 'Seite/Beitrag',
					'name' => 'post',
					'type' => 'post_object',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'field_54a7e2a3e2625',
								'operator' => '==',
								'value' => 'Seite/Beitrag',
							),
						),
					),
					'wrapper' => array (
						'width' => 25,
						'class' => '',
						'id' => '',
					),
					'post_type' => array (
						0 => 'page',
						1 => 'post',
					),
					'taxonomy' => array (
					),
					'allow_null' => 0,
					'multiple' => 0,
					'return_format' => 'object',
					'ui' => 1,
				),
				array (
					'key' => 'field_54a7e2a3e2628',
					'label' => 'Medienbeitrag',
					'name' => 'media-item',
					'type' => 'file',
					'instructions' => 'Eine Referenz auf ein Dokument in der Medien-Bibliothek',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'field_54a7e2a3e2625',
								'operator' => '==',
								'value' => 'Medienbeitrag',
							),
						),
					),
					'wrapper' => array (
						'width' => 25,
						'class' => '',
						'id' => '',
					),
					'return_format' => 'array',
					'library' => 'all',
					'min_size' => 0,
					'max_size' => 0,
					'mime_types' => '',
				),
				array (
					'key' => 'field_54a7e2a3e2629',
					'label' => 'Link',
					'name' => 'link-url',
					'type' => 'url',
					'instructions' => 'Volle URL im Format "http://example.com/page"',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'field_54a7e2a3e2625',
								'operator' => '==',
								'value' => 'Link',
							),
						),
					),
					'wrapper' => array (
						'width' => 25,
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
				),
				array (
					'key' => 'field_54a7e2a3e262c',
					'label' => 'Alternativtext',
					'name' => 'alt',
					'type' => 'text',
					'instructions' => 'Wird als Linktext verwendet, falls eingetragen',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => 25,
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
					'readonly' => 0,
					'disabled' => 0,
				),
			),
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'page',
			),
		),
	),
	'menu_order' => 20,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => array (
		0 => 'custom_fields',
		1 => 'discussion',
		2 => 'comments',
		3 => 'revisions',
		4 => 'slug',
		5 => 'format',
		6 => 'tags',
		7 => 'send-trackbacks',
	),
	'active' => 1,
	'description' => '',
	'local' => 'php',
));

endif;
//---------------------------------

}
?>